services:
  - type: web
    name: pocket-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
  - key: TELEGRAM_TOKEN
    fromEnvVar: TELEGRAM_TOKEN
  - key: TELEGRAM_CHAT_ID
    fromEnvVar: TELEGRAM_CHAT_ID
   - key: DASHBOARD_PORT
        value: 8501
