services:
  - type: web
    name: pocket-option-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port 8080 --server.address 0.0.0.0
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id_here
